name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # NumberInWords

    - name: NumberInWords
      run: dotnet restore ./src/*/NumberInWords.csproj

    - name: Build NumberInWords
      run: dotnet build ./src/*/NumberInWords.csproj --no-restore  -c Release

    - name: Pack NumberInWords
      run: dotnet pack ./src/*/NumberInWords.csproj --no-restore -o ~/nuget  -c Release

    # NumberInWords.Test

    - name: Test NumberInWords
      run: dotnet test ./src/*/NumberInWords.Test.csproj -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ vars.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate
